<!DOCTYPE html>
<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title><?php echo $cedente; ?></title>
    <style type="text/css">
        /* Embed the CSS content here */
        <?php include $resource_path . '/css/styles.css' ?>

        .div-carne:nth-child(3n) {
            page-break-after: always;
        }
    </style>

</head>
<body>
    <div class="div-carne" style="width: 876px;height: 9.7cm;margin-top: 50px;margin-bottom: 50px;">
        <div style="float: left">
            <table class="table-boleto" style="width: 180px" cellpadding="0" cellspacing="0" border="0">

                <tr>
                    <td>
                        <div class="titulo">Sacado</div>
                        <div class="conteudo"><?php echo $sacado ?></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="titulo">Vencimento</div>
                        <div class="conteudo"><?php echo $data_vencimento ?></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="titulo">Agência/Código do Cedente</div>
                        <div class="conteudo"><?php echo $agencia_codigo_cedente ?></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="titulo">Nosso número</div>
                        <div class="conteudo"><?php echo $nosso_numero ?></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="titulo">Nº documento</div>
                        <div class="conteudo"><?php echo $numero_documento ?></div>
                    </td>
                </tr>

                <?php if($imgPIx == null): ?>

                <tr>
                    <td>
                        <div class="titulo">Espécie</div>
                        <div class="conteudo"><?php echo $especie ?></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="titulo">Quantidade</div>
                        <div class="conteudo"><?php echo $quantidade ?></div>
                    </td>
                </tr>

                <?php endif; ?>


                <tr>
                    <td>
                        <div class="titulo">(=) Valor Documento</div>
                        <div class="conteudo"><?php echo $valor_documento ?></div>
                    </td>
                </tr>

                <?php if($imgPIx == null): ?>
              
                <tr>
                    <td>
                        <div class="titulo">(+) Mora / Multa</div>
                        <div class="conteudo"><?php echo $mora_multa ?></div>
                    </td>
                </tr>
              
                <tr>
                    <td class="bottomborder">
                        <div class="titulo">(=) Valor cobrado</div>
                        <div class="conteudo"><?php echo $valor_cobrado ?></div>
                    </td>
                </tr>

                <?php endif; ?>
            </table>
            <?php if($imgPIx == null): ?>
            <span class="header">Recibo do Sacado</span>
            <?php endif; ?>

            <?php if($imgPIx != null): ?>

                <span class="header">Pague com pix</span>

                <?php
                $base64 = base64_encode($imgPIx);
                ?>
        
                <img src="data:image/png;base64,<?php echo $base64; ?>" alt="" width="155" />

           <?php endif; ?>


        </div>
        <div style="float: left; margin-left: 30px">
            <!-- Ficha de compensação -->
            <?php include('partials/ficha-de-compensacao.phtml') ?>
        </div>
        <div style="clear: both"></div>
        <br>
        <!-- <div class="linha-pontilhada">&nbsp;</div> -->
    </div>

</body>
</html>

