<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Medicamento;
use Faker\Generator as Faker;

$factory->define(Medicamento::class, function (Faker $faker) {

    $componente = [
        'ABATACEPTE',
        'ACIDO ZOLEDRONICO',
        'ACETADO FLUDROCORTISONA',
        'ACETATO DE ABIRATERONA',
        'ACETATO DE CASPOFUNGINA',
        'ACETATO DE DEGARELIX',
        'ACETATO DE LANREOTIDA',
        'ACETATO DE LEUPRORRELINA',
        'ACETATO DE TERLIPRESSINA',
        'ADALIMUMABE',
        'AFATINIB',
        'AFLIBERCEPTE',
        'ALBUMINA HUMANA (Albumax)',
        'ALFADARBEPOETINA',
        'ALFAEPOETINA',
        'ALFATIROTROPINA',
        'ALTEPLASE',
        'AMBRISENTANA',
        'ANASTROZOL',
        'ANFOTERICINA B LIPOSSOMAL',
        'APREPITANO',
        'AZACITIDINA',
        'AZATIOPRINA',
        'CABAZITAXEL',
        'CAPECITABINA',
        'CANAQUINUMABE',
        'CAPECITABINA',
        'CARBOPLATINA',
        'CARBOXIMALTOSE FERRICA',
        'CERTOLIZUMABE PEGOL',
        'CETUXIMABE',
        'CICLOFOSFAMIDA',
        'CICLOSPORINA',
        'CIPROTERONA',
        'CISPLATINA',
        'CITARABINA',
        'CL DE DOXO LIPOSSOMAL',
        'CLODRONATO DISSODICO',
        'CLOR. DOXORRUBICINA',
        'CLOR. VANCICLOVIR',
        'CLORAMBUCILA',
        'CLORIDRATO DE CINACALCETE',
        'CLORIDRATO DE DOXORRUBICINA',
        'CLORIDRATO DE EPIRRUBICINA',
        'CLORIDRATO DE ERLOTINIBE',
        'CLORIDRATO DE GENCITABINA',
        'CLORIDRATO DE IRINOTECANO',
        'CLORIDRATO DE ONDANSENTRONA',
        'CLORIDRATO DE ONDANSETRANA',
        'CLORIDRATO DE SEVELÂMER',
        'CLORIDRATO IRINOTECANA',
        'CLORIDRATO IRINOTECANO',
        'COMPLEXO LIP DE ANFOTERICINA B',
        'PACLITAXEL',
        'PANITUMUMAB',
        'PARICALCITOL',
        'PAZOPANIBE',
        'PEG INTERFERONA',
        'PEGFILGRASTIM',
        'PEGVISOMANTO',
        'PEMBROLIZUMABE',
        'PEMETREXEDE',
        'PEMETREXEDE DISSODICO',
        'PERTUZUMAB',
        'PIRFENIDONA',
        'POLIESTIRENOSSULFONATO',
        'POSACONAZOL',
        'PREMEXEDE',
        'PREMEXEDE DISSODICO',
    ];

    return [
        'componente' => $faker->randomElement($componente),
        'quantidade' => $faker->randomDigit,
        'unidade' => $faker->randomElement($array = ['mg','ml','g','com','dose']),
    ];
});
